### ISSUE TITLE
IllegalArgumentException after opening the liferay-portal/modules project

### ISSUE THREAD

**Issue by dantewang** [liferay/liferay-intellij-plugin#106]
When opening project which is imported from liferay-portal/modules using Gradle with the intellij-plugin installed, `IllegalArgumentException` is thrown:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at com.liferay.ide.idea.util.LiferayWorkspaceUtil.getTargetPlatformArtifacts(LiferayWorkspaceUtil.java:185)
	at com.liferay.ide.idea.language.javascript.LiferayJSPredefinedLibraryProvider._getTargetPlatformArtifacts(LiferayJSPredefinedLibraryProvider.java:205)
	at com.liferay.ide.idea.language.javascript.LiferayJSPredefinedLibraryProvider._getJavascriptFiles(LiferayJSPredefinedLibraryProvider.java:126)
	at com.liferay.ide.idea.language.javascript.LiferayJSPredefinedLibraryProvider.lambda$rootsChanged$1(LiferayJSPredefinedLibraryProvider.java:102)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:445)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jtydhr88** [comment]
hey @dmarks2 it seems relating to the frontend/javascript support, please let me know if you have time to take a look at it, otherwise I can investigate it, thanks.

**Comment by dmarks2** [comment]
hey @jtydhr88 it seems to have something to do with the `LiferayWorkspaceUtil.getTargetPlatformArtifacts() `method. 

It seems that the sorting for the artifacts is not correct. As far as I understand it, it does not handle `null` values correctly. I can have a look at it and see if I can fix it.

Can you create a JIRA issue for this?

**Comment by jtydhr88** [comment]
hey @dmarks2 open here https://issues.liferay.com/browse/INTELLIJ-67

**Comment by jtydhr88** [comment]
hey @gamerson can you close it, it should be fixed.
