### ISSUE TITLE
Liferay Plugin 1.7.4 failing on Intellij 2020.2.2 CE

### ISSUE THREAD

**Issue by ankurjhawar** [liferay/liferay-intellij-plugin#128]
Hello,

I am using  Intellij 2020.2.2 CE with Liferay Plugin 1.7.4 and it fails with the following exception:

com.intellij.diagnostic.PluginException: Cannot create class com.liferay.ide.idea.core.LiferayPostStartupActivity [Plugin: com.liferay.ide.intellij.plugin]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:656)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:50)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:133)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:42)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:480)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:421)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.calcExtensionList(ExtensionPointImpl.java:248)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:242)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$scheduleBackgroundPostStartupActivities$6(StartupManagerImpl.java:408)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/javaee/web/facet/WebFacetType
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:613)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.intellij.javaee.web.facet.WebFacetType PluginClassLoader[PluginDescriptor(name=Liferay, id=com.liferay.ide.intellij.plugin, path=C:\Users\ajhawar\AppData\Roaming\JetBrains\IdeaIC2020.2\plugins\liferay-intellij-plugin, version=1.7.4)] com.intellij.ide.plugins.cl.PluginClassLoader@3151874a
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 25 more

From the plugin [documentation ](https://plugins.jetbrains.com/plugin/10739-liferay/versions) it seems it should be supporting the version I am on with CE:

![image](https://user-images.githubusercontent.com/7464166/93720481-e3032b00-fba6-11ea-93f0-fab17326fcfc.png)

Can you please check and confirm whether its a really an issue with the plugin or whether its a compatibility problem and how to address it?

Thanks!

**Comment by dmarks2** [comment]
This is probably related to https://issues.liferay.com/browse/INTELLIJ-125

**Comment by jtydhr88** [comment]
I am using IDEA 2020.2.1 with liferay plugin 1.8.1 and it works for me. You could try the latest version of liferay version.
