### ISSUE TITLE
Liferay Plugins 1.9.2 / IntelliJ 2021.1.2 throws Nullpointer on MacOS 11.4 

### ISSUE THREAD

**Issue by horstLei** [liferay/liferay-intellij-plugin#135]
hi. it seems with the new version 11.4 there is a File access Problem which throws a Nullpointer 

`java.lang.NullPointerException
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:271)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.liferay.ide.idea.server.LiferayServerConfiguration.clone(LiferayServerConfiguration.java:148)
	at com.intellij.execution.configurations.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:41)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:256)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic(RunConfigurationProducer.java:260)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration(RunConfigurationProducer.java:250)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:99)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:200)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:110)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:93)
	at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:135)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:32)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:184)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:175)
	at com.intellij.execution.testframework.TestFailedLineInspection$RunActionFix.<init>(TestFailedLineInspection.java:83)
	at com.intellij.execution.testframework.TestFailedLineInspection$DebugFailedTestFix.<init>(TestFailedLineInspection.java:58)
	at com.intellij.execution.testframework.TestFailedLineInspection$1.visitMethodCallExpression(TestFailedLineInspection.java:42)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:125)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

first I thought its the runtime config / one path was moved but no all are correct / also annoying on this one on ALL windows/Projects the the red exclamation mark is popping up also if removed (clear all) it's coming soon back...

good wood be also to know which project (if it's the config) is involved 

how can I solve this ? (at the moment the error popup says disable the plugin ... hmm )

br horst

**Comment by yanan** [comment]
Hello @horstLei ,

Thanks for the report. And we've fixed this in this ticket [INTELLIJ-200](https://issues.liferay.com/browse/INTELLIJ-200), will release a new 1.9.3 soon.

**Comment by yanan** [comment]
Hello @horstLei , here is the new 1.9.3 plugin which fixed the problem:
https://plugins.jetbrains.com/files/10739/122894/liferay-intellij-plugin-1.9.3.zip

**Comment by horstLei** [comment]
perfect issue solved 
thnx for your fast work :-)
