### ISSUE TITLE
IllegalArgumentException: invalid version "1.8.0_312": non-numeric "0_312"

### ISSUE THREAD

**Issue by ybroeker** [liferay/liferay-intellij-plugin#174]
When starting the liferay server via IntelliJ IDEA, parsing the JDK version fails for some JDKs and the server cannot be started. This happens e.g. with the 1.8-JDKs installed directly via IntelliJ (e.g. `corretto-1.8.0_312`).

<details>
  <summary>Stacktrace</summary>
  
  ```
java.lang.IllegalArgumentException: invalid version "1.8.0_312": non-numeric "0_312"
	at org.osgi.framework.Version.parseInt(Version.java:170)
	at org.osgi.framework.Version.<init>(Version.java:134)
	at org.osgi.framework.Version.valueOf(Version.java:257)
	at org.osgi.framework.Version.parseVersion(Version.java:228)
	at com.liferay.ide.idea.server.portal.PortalTomcatBundle._getRuntimeVMArgs(PortalTomcatBundle.java:105)
	at com.liferay.ide.idea.server.portal.PortalTomcatBundle.getRuntimeStartVMArgs(PortalTomcatBundle.java:81)
	at com.liferay.ide.idea.server.LiferayServerCommandLineState.createJavaParameters(LiferayServerCommandLineState.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:44)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:137)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecute$3(DefaultJavaProgramRunner.java:127)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$patchJavaCommandLineParamsUnderProgress$2(JavaProgramPatcher.java:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:298)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NumberFormatException: For input string: "0_312"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.osgi.framework.Version.parseInt(Version.java:168)
	... 34 more
```
</details>

**Comment by jtydhr88** [comment]
hi @ybroeker, I guess the plug-in would not support 1.8 version of Java , can you try some newer one, such as Java 11?

**Comment by ybroeker** [comment]
Since the error is in code that is explicitly there for Java 8, that would not be necessary if Java 8 is not supported?
The Java version itself does not trigger the error, but the parsing of the version with `org.osgi.framework.Version`, which cannot parse JDK versions.

Locally I already fixed the problem, I can submit a pull request later.

**Comment by rahmatjafari** [comment]
Thanks @ybroeker. It worked for me.

**Comment by simonjhy** [comment]
it was fixed https://github.com/liferay/liferay-intellij-plugin/pull/176, thanks @ybroeker
