### ISSUE TITLE
Liferay plugin 2.0.0 for IntelliJ does not recognizes the Java version in case underscore is present(e.g. 1.8.0_292)

### ISSUE THREAD

**Issue by rosenhristov** [liferay/liferay-intellij-plugin#183]
I get the following exception when I try to start a Liferay application using IntelliJ IDEA with the Liferay plugin. It cannot recognize the Java version if it contains underscore, e.g. 1.8.0_292. I tried to change the version but it still complains for this one in particular:
```
java.lang.IllegalArgumentException: invalid version "1.8.0_292": non-numeric "0_292"
	at org.osgi.framework.Version.parseInt(Version.java:170)
	at org.osgi.framework.Version.<init>(Version.java:134)
	at org.osgi.framework.Version.valueOf(Version.java:257)
	at org.osgi.framework.Version.parseVersion(Version.java:228)
	at com.liferay.ide.idea.server.portal.PortalTomcatBundle._getRuntimeVMArgs(PortalTomcatBundle.java:105)
	at com.liferay.ide.idea.server.portal.PortalTomcatBundle.getRuntimeStartVMArgs(PortalTomcatBundle.java:81)
	at com.liferay.ide.idea.server.LiferayServerCommandLineState.createJavaParameters(LiferayServerCommandLineState.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:44)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:137)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecute$3(DefaultJavaProgramRunner.java:127)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$patchJavaCommandLineParamsUnderProgress$2(JavaProgramPatcher.java:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:298)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NumberFormatException: For input string: "0_292"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.osgi.framework.Version.parseInt(Version.java:168)
	... 34 more
	```

**Comment by yanan** [comment]
Hello, 
Thanks for reporting. The problem has been fixed on https://issues.liferay.com/browse/INTELLIJ-223. Here is a snapshot if you would like to try. Please feel free to let us know if there is anything.
[liferay-intellij-plugin-2.0.1.zip](https://github.com/liferay/liferay-intellij-plugin/files/8121217/liferay-intellij-plugin-2.0.1.zip)
