### ISSUE TITLE
"Portal bundle type is invalid" after upgrading to 2.0.2

### ISSUE THREAD

**Issue by rimesc** [liferay/liferay-intellij-plugin#231]
After upgrading to version 2.0.2 of the plugin and attempting to launch Liferay, I get the following error:

> **Error running 'Liferay 7.3.6 GA 7'**
> Liferay bundle location is invalid.
> /path/to/project/bundles/tomcat-9.0.40

Editing the launch configuration displays the following error at the bottom of the dialog:

> **Invalid Data:** Portal bundle type is invalid

Newly-created launch configurations have the same error.

### Stack trace
```
com.intellij.execution.ExecutionException: Liferay bundle location is invalid.  /path/to/project/bundles/tomcat-9.0.40
	at com.liferay.ide.idea.server.LiferayServerCommandLineState.createJavaParameters(LiferayServerCommandLineState.java:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:137)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecute$3(DefaultJavaProgramRunner.java:127)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$patchJavaCommandLineParamsUnderProgress$2(JavaProgramPatcher.java:43)
	...
```

As a workaround, running InitBundle to download a new Liferay bundle fixes the issue, but at the expense of throwing away all of your data and custom configuration.

**Comment by simonjhy** [comment]
I tested with a customized bundles location and I did not reproduce your error. Here is scrren snapshot 
![Screenshot from 2022-11-28 16-12-26](https://user-images.githubusercontent.com/5745444/204226699-a0bd6bb1-08ee-4f31-8ddf-88f02af3e0c0.png)
