### ISSUE TITLE
Workspace and module creation not working in 2023.2.1

### ISSUE THREAD

**Issue by LouisDeGuinness** [liferay/liferay-intellij-plugin#282]
After updating to 2023.2.1 trying to create a workspace fails on fetching portal versions:

`java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:652)
	at com.liferay.ide.idea.ui.modules.LiferayWorkspaceBuilder.lambda$_initProductVersionComBox$6(LiferayWorkspaceBuilder.java:311)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

And it doesn't show any templates for module creation, perhaps related?

I'm using the 2.0.5 plugin version

**Comment by Zackmon** [comment]
I am facing the same issue, causing an error when selecting a project type while creating a new Liferay Module. 


I had to revert back to Intellj 2023.1.5

<img width="939" alt="Screenshot 2023-08-26 at 9 09 43 AM" src="https://github.com/liferay/liferay-intellij-plugin/assets/1449870/f55183cc-7fce-4fc5-ad52-1338f9952c9c">

**Comment by LouisDeGuinness** [comment]
In 2023.2 also working without a problem.

**Comment by simonjhy** [comment]
I used Idea 2023.2.1 + liferay plgin 2.0.5 and I did not get this error. It could correctly show product version. Can you help to use blade command in command line to test with "blade init -l" to confirm whether blade can get product verison?

**Comment by JaimeReyBabel** [comment]
I have the same problem creating new modules. I'm using IJ2023.2.2 and Liferay plugin 2.0.5.
I can only create modules via blade CLI.
blade init -I outputs:
>blade init -l
> dxp-7.4-u95
> dxp-7.4-u10
> dxp-7.3-u33
> dxp-7.2-sp8
> dxp-7.1-sp8
> dxp-7.1-fp27
> dxp-7.0-sp17
> portal-7.4-ga95
> portal-7.4-ga61
> portal-7.3-ga8
> portal-7.2-ga2
> portal-7.1-ga4
> portal-7.0-ga7
> commerce-2.0.7-7.2
> commerce-2.0.7-7.1

And I have this in gradle.properties:
>liferay.workspace.product=dxp-7.0-sp17

**Comment by simonjhy** [comment]
we released new version plugin. Can you try to check it again?

**Comment by JaimeReyBabel** [comment]
Updated and tested; them module creation wizard seems to work now.

**Comment by LouisDeGuinness** [comment]
Can confirm. Working as expected.
