### ISSUE TITLE
Exception thrown from Liferay plugin 2.1.0 and Intellij community 2024.2.4

### ISSUE THREAD

**Issue by rana-kader** [liferay/liferay-intellij-plugin#311]
Exception thrown after installing the plugin and stack trace as below:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.liferay.ide.idea.ui.modules.ext.NewModuleExtFilesAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.liferay.ide.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by drewbrokke** [comment]
@rana-kader thanks for raising this issue. Does this exception prevent startup or usage of IntelliJ or the plugin? Or is it primarily a warning?
