### ISSUE TITLE
Exception in Plugin 2.1.1 und Intellij 2024.3.1

### ISSUE THREAD

**Issue by LouisDeGuinness** [liferay/liferay-intellij-plugin#312]
If i right click on a module in file view, an error occurs:

> LiferayActionGroup#presentation@ProjectViewPopup (com.liferay.ide.idea.ui.actions.LiferayActionGroup), actionId=LiferayActionGroup, text='Liferay'
> 
> java.lang.IllegalAccessError: class com.liferay.ide.idea.util.GradleUtil tried to access private field org.jetbrains.plugins.gradle.settings.GradleExtensionsSettings$GradleTask.name (com.liferay.ide.idea.util.GradleUtil is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @348d3bc1; org.jetbrains.plugins.gradle.settings.GradleExtensionsSettings$GradleTask is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @636dbf23)
> 	at com.liferay.ide.idea.util.GradleUtil.lambda$isWatchableProject$8(GradleUtil.java:381)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1778)
> 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
> 	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.tryAdvance(Collections.java:1797)
> 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
> 	at com.liferay.ide.idea.util.GradleUtil.isWatchableProject(GradleUtil.java:384)
> 	at com.liferay.ide.idea.ui.actions.WatchGradleModuleAction.isEnabledAndVisible(WatchGradleModuleAction.java:147)
> 	at com.liferay.ide.idea.ui.actions.LiferayActionGroup.lambda$update$3(LiferayActionGroup.java:49)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
> 	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:709)
> 	at com.liferay.ide.idea.ui.actions.LiferayActionGroup.update(LiferayActionGroup.java:50)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate$lambda$2(ActionUtil.kt:226)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.kt:244)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1$1.invoke(ActionUpdater.kt:501)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1$1.invoke(ActionUpdater.kt:500)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$2$1.invoke(ActionUpdater.kt:145)
> 	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
> 	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
> 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
> 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
> 	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
> 	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
> 	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
> 	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
> 	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
> 	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invokeSuspend(InternalReadAction.kt:36)
> 	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
> 	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
> 	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
> 	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:35)
> 	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
> 	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
> 	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionUndispatched(coroutines.kt:86)
> 	at com.intellij.openapi.application.CoroutinesKt.readActionUndispatched(coroutines.kt:73)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invokeSuspend(trace.kt:61)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.kt:882)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$callAction(ActionUpdater.kt:77)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1.invokeSuspend(ActionUpdater.kt:500)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1.invoke(ActionUpdater.kt)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1.invoke(ActionUpdater.kt)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invokeSuspend(ActionUpdater.kt:831)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateAction(ActionUpdater.kt:933)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.kt:347)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$expandGroupChild(ActionUpdater.kt:77)
> 	at com.intellij.openapi.actionSystem.impl.ActionUpdater$doExpandActionGroup$2$expandResult$1$1.invokeSuspend(ActionUpdater.kt:274)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
> 

Besides that plugin is working fine but context menu (right click on module folder) doesn't offer Liferay options anymore (deploy, watch, ...).

**Comment by LouisDeGuinness** [comment]
I fixed it with a workaround but there will be a better way so i won't make a pull request. But the problem is gone if i change following in GradleUtil:

```
return gradleExtensionsData.tasksMap.entrySet(
    ).stream(
    ).map(
      entry -> entry.getValue()
    ).filter(
      task -> Objects.equals(task.name, "watch")
    ).filter(
      task -> Objects.deepEquals("com.liferay.gradle.plugins.task.WatchTask", task.typeFqn)
    ).findAny(
    ).isPresent();
}
```
to
```
return gradleExtensionsData.tasksMap.entrySet(
        ).stream(
        ).map(
            entry -> entry.getValue()
        ).filter(
            task -> Objects.equals(_getTaskFieldByReflection(task, "name"), "watch")
        ).filter(
            task -> Objects.deepEquals("com.liferay.gradle.plugins.task.WatchTask", _getTaskFieldByReflection(task, "typeFqn"))
        ).findAny(
        ).isPresent();
    }

    private static String _getTaskFieldByReflection(GradleExtensionsSettings.GradleTask task, String fieldName) {

        try {
            Field field = GradleExtensionsSettings.GradleTask.class.getDeclaredField(fieldName);
            field.setAccessible(true);
            return (String) field.get(task);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            return "";
        }
    }
```

**Comment by drewbrokke** [comment]
@LouisDeGuinness I see it's been awhile here, wanted to see if this problem persists with the newest release (`3.1.0`).

**Comment by LouisDeGuinness** [comment]
No, it's fine now

**Comment by drewbrokke** [comment]
Ok, glad to hear it!
