### ISSUE TITLE
liferay tomcat path error

### ISSUE THREAD

**Issue by JesseRo** [liferay/liferay-intellij-plugin#64]
![98br4k5wrh9l2b d706n 2](https://user-images.githubusercontent.com/14294862/44070325-cb561a2a-9fb5-11e8-9710-ae480c3c2a3e.png)
The plugin worked well, till i reboot my computer..

**Comment by gamerson** [comment]
hey @jtydhr88  could you take a look?

**Comment by jtydhr88** [comment]
hey @JesseRo what’s your full location of the portal?

**Comment by JesseRo** [comment]
@jtydhr88 
_C:/dev/liferay-ce-portal-7.0-ga3_
 is the portal location.
_C:/Users/Jesse/Document/UserSync_
 is a liferay workspace module

**Comment by jtydhr88** [comment]
hey @JesseRo can you post the page of your server config?

**Comment by jtydhr88** [comment]
also can you post the full error log? thanks a lot

**Comment by JesseRo** [comment]
the thing is that the server config page is not available..
![r 3eg2 d79 nkxxghy80dm](https://user-images.githubusercontent.com/14294862/44132345-a097bbdc-a08b-11e8-8e63-4ff7e1c1598d.png)

here is the full log:
Illegal char <:> at index 35: C:/Users/Jesse/Documents/UserSync\C:\dev\liferay-ce-portal-7.0-ga3
java.nio.file.InvalidPathException: Illegal char <:> at index 35: C:/Users/Jesse/Documents/UserSync\C:\dev\liferay-ce-portal-7.0-ga3
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.liferay.ide.idea.server.LiferayServerConfiguration.<init>(LiferayServerConfiguration.java:74)
	at com.liferay.ide.idea.server.LiferayServerConfigurationType$1.createTemplateConfiguration(LiferayServerConfigurationType.java:42)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:76)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$lang_impl(RunManagerImpl.kt:253)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:240)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:169)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.java:1077)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction.a(RunConfigurable.java:1111)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:82)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:48)
	at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:403)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:355)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:510)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:574)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:736)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:458)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1686)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1635)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by JesseRo** [comment]
i believe it's 1.0.0
i manually download the .zip file and _install plugin from disk_

**Comment by jtydhr88** [comment]
can you help to check version in your IntelliJ plugin page?

**Comment by JesseRo** [comment]
![2 qx c5 r q sre423w01](https://user-images.githubusercontent.com/14294862/44133520-c055c322-a092-11e8-8bab-f2d408366ef4.png)
that is the plugin setting page.

**Comment by jtydhr88** [comment]
hey @JesseRo thanks a lot, we have reproduce this error and we will fix it soon. thanks again.

**Comment by JesseRo** [comment]
glad to help :)

**Comment by jtydhr88** [comment]
Actually we already fix it on the master, if you would like that you can build the plugin locally(see the home page), but I want to add more validation in next release

**Comment by jtydhr88** [comment]
fixed by https://github.com/liferay/liferay-intellij-plugin/commit/bd4831b7f7aca4f245cc803bf9ee83b370f9dd72
