### ISSUE TITLE
bug: Content equals, but it must be handled not on this level: file rest_main.iml

### ISSUE THREAD

**Issue by Camork** [liferay/liferay-intellij-plugin#73]
### How to reproduce:
I'm working on this workspace [liferay-blade-samples](https://github.com/liferay/liferay-blade-samples/tree/master/liferay-workspace), this error happend after gradle building

```
Content equals, but it must be handled not on this level: file rest_main.iml, content
<module external.linked.project.id=":apps:rest:main" external.linked.project.path="$MODULE_DIR$/../../../../apps/rest" external.root.project.path="$MODULE_DIR$/../../../.." external.system.id="GRADLE" external.system.module.group="liferay-workspace.apps" external.system.module.type="sourceSet" external.system.module.version="1.0.0" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8">
    <output url="file://$MODULE_DIR$/../../../../apps/rest/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../apps/rest/src/main">
      <sourceFolder url="file://$MODULE_DIR$/../../../../apps/rest/src/main/java" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/../../../../apps/rest/src/main/resources" type="java-resource" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: javax.ws.rs:javax.ws.rs-api:2.0.1" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: com.liferay.portal:com.liferay.portal.kernel:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: org.osgi:osgi.core:5.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: org.osgi:osgi.cmpn:6.0.0" level="project" />
  </component>
</module>
java.lang.Throwable: Content equals, but it must be handled not on this level: file rest_main.iml, content
<module external.linked.project.id=":apps:rest:main" external.linked.project.path="$MODULE_DIR$/../../../../apps/rest" external.root.project.path="$MODULE_DIR$/../../../.." external.system.id="GRADLE" external.system.module.group="liferay-workspace.apps" external.system.module.type="sourceSet" external.system.module.version="1.0.0" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8">
    <output url="file://$MODULE_DIR$/../../../../apps/rest/out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../../../apps/rest/src/main">
      <sourceFolder url="file://$MODULE_DIR$/../../../../apps/rest/src/main/java" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/../../../../apps/rest/src/main/resources" type="java-resource" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: javax.ws.rs:javax.ws.rs-api:2.0.1" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: com.liferay.portal:com.liferay.portal.kernel:3.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: org.osgi:osgi.core:5.0.0" level="project" />
    <orderEntry type="library" scope="PROVIDED" name="Gradle: org.osgi:osgi.cmpn:6.0.0" level="project" />
  </component>
</module>
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:195)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:100)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:137)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:85)
	at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:542)
	at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:282)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:172)
	at com.intellij.openapi.components.impl.stores.IComponentStore$DefaultImpls.save$default(IComponentStore.kt:29)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.beforeSave(ProjectStoreImpl.kt:373)
	at com.intellij.configurationStore.ProjectStoreImpl.doSave(ProjectStoreImpl.kt:314)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:172)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:40)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:331)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:315)
	at com.liferay.ide.idea.project.LiferayProjectComponent._addWebRoot(LiferayProjectComponent.java:120)
	at com.liferay.ide.idea.project.LiferayProjectComponent.access$000(LiferayProjectComponent.java:43)
	at com.liferay.ide.idea.project.LiferayProjectComponent$1.moduleAdded(LiferayProjectComponent.java:69)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy95.moduleAdded(Unknown Source)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAdded(ModuleManagerImpl.java:386)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$commitModel$5(ModuleManagerImpl.java:1012)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:330)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:966)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1500(ModuleManagerImpl.java:64)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:874)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1200(ModuleManagerImpl.java:640)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:631)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:50)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:39)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.c(AbstractIdeModifiableModelsProvider.java:440)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:295)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:414)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl$2.execute(ProjectDataManagerImpl.java:432)
	at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.lambda$executeProjectChangeAction$6(ExternalSystemApiUtil.java:469)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Camork** [comment]
Moved to https://issues.liferay.com/browse/INTELLIJ-4
